CREATE TABLE [Auth].[AspNetRoles](
	[Id] NVARCHAR(36) NOT NULL,
	[Name] NVARCHAR(256) NULL,
	[NormalizedName] NVARCHAR(256) NULL,
	[ConcurrencyStamp] NVARCHAR(MAX) NULL,
	CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE INDEX [RoleNameIndex] ON [Auth].[AspNetRoles] ([NormalizedName]) WHERE [NormalizedName] IS NOT NULL;