CREATE TABLE [Auth].[AspNetUserRoles](
	[UserId] NVARCHAR(36) NOT NULL,
	[RoleId] NVARCHAR(36) NOT NULL,
	 CONSTRAINT [PK_Auth_AspNetUserRoles] PRIMARY KEY CLUSTERED 
	(
		[UserId] ASC,
		[RoleId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY([RoleId]) REFERENCES [Auth].[AspNetRoles]([Id]),
	CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY([UserId]) REFERENCES [Auth].[AspNetUsers]([Id])
) ON [PRIMARY]
GO
CREATE INDEX [IX_AspNetUserRoles_RoleId] ON [Auth].[AspNetUserRoles] ([RoleId])